apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  Postgres_User: cG9zdGdyZXNhZG1pbg==
  Postgres_Password: YWRtaW4xMjM=

---
apiVersion: v1
kind: Service
metadata:
  name: service-auth
  labels:
    app: soa
spec:
  ports:
    - port: 8080
  type: LoadBalancer
  selector:
    app: soa
    tier: service-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  labels:
    app: soa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soa
      tier: service-auth
  template:
    metadata:
      labels:
        app: soa
        tier: service-auth
    spec:
      containers:
        - name: service-auth
          image: trip/service-auth
          ports:
            - containerPort: 8080
              name: service-auth
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/users
            - name: SPRING_DATASOURCE_USERNAME
              value: postgresadmin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin123
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_SQL_INIT_MODE
              value: always
          imagePullPolicy: Never