apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-booking
  labels:
    app: soa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soa
      tier: service-booking
  template:
    metadata:
      labels:
        app: soa
        tier: service-booking
    spec:
      containers:
        - name: service-booking
          image: your-service-booking-image
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: service-booking
  labels:
    app: soa
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: soa
    tier: service-booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-booking
  labels:
    app: soa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soa
      tier: service-booking
  template:
    metadata:
      labels:
        app: soa
        tier: service-booking
    spec:
      containers:
        - name: service-recommend
          image: trip/service-recommend
          ports:
            - containerPort: 8084
              name: service-recommend
          imagePullPolicy: Never
        - name: service-reserve
          image: trip/service-reserve
          ports:
            - containerPort: 8085
              name: service-reserve
          imagePullPolicy: Never
        - name: service-select
          image: trip/service-select
          ports:
            - containerPort: 8086
              name: service-select
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: service-recommend
  labels:
    app: soa
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: soa
    tier: service-booking
---
apiVersion: v1
kind: Service
metadata:
  name: service-reserve
  labels:
    app: soa
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: soa
    tier: service-booking
---
apiVersion: v1
kind: Service
metadata:
  name: service-select
  labels:
    app: soa
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: soa
    tier: service-booking
