# STAGE 1 - from Dockerfile.dependencies file
FROM eclipse-temurin as deps
# STAGE 1 - Download dependencies
WORKDIR /app
COPY gradlew .
COPY build/gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN ./gradlew dependencies
RUN ./gradlew copyDependencies

# STAGE 2 - Build

FROM deps as build
COPY src src
COPY --from=deps /app/libs libs
RUN ./gradlew build -Dorg.gradle.java.home=/opt/java/openjdk -Duser.home=/tmp/gradle_home

#STAGE 3 - Add a volume
FROM build as addVolume
VOLUME /shared-volume
RUN mkdir /shared-data
RUN cp gradlew /shared-data